# Generated by Django 4.2.30 on 2026-07-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('records_synced', models.PositiveSmallIntegerField(default=0)),
                ('records_failed', models.PositiveSmallIntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
