# Generated by Django 4.2.30 on 2026-07-09 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('improvement', models.DecimalField(decimal_places=2, help_text='current_score - previous_score. Primary leaderboard ranking field.', max_digits=5, null=True)),
                ('total_assessments', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.assessmentsession')),
                ('previous_session', models.ForeignKey(help_text='Session before latest, used to calculate improvement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.assessmentsession')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='students.student')),
            ],
            options={
                'db_table': 'leaderboard_snapshots',
                'ordering': ['-improvement', '-current_score'],
            },
        ),
    ]
