# Generated by Django 4.2.30 on 2026-07-09 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_templates',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pillars', to='assessments.assessmenttemplate')),
            ],
            options={
                'db_table': 'pillars',
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_sport_specific', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='assessments.pillar')),
            ],
            options={
                'db_table': 'criteria',
                'ordering': ['order'],
                'unique_together': {('pillar', 'order')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('martial_art', models.CharField(choices=[('boxing', 'Boxing'), ('kickboxing', 'Kickboxing')], max_length=12)),
                ('assessment_date', models.DateField(db_index=True)),
                ('sessions_completed', models.PositiveSmallIntegerField(default=0)),
                ('coach_notes', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('grade_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('level_at_assessment', models.CharField(blank=True, max_length=14)),
                ('synced_from_sheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmenttemplate')),
            ],
            options={
                'db_table': 'assessment_sessions',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='PillarScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.pillar')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pillar_scores', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'pillar_scores',
                'unique_together': {('session', 'pillar')},
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boxing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('kickboxing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('effective_score', models.DecimalField(decimal_places=2, help_text='Calculated by engine: average of filled scores.', max_digits=4, null=True)),
                ('coach_comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.criterion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_scores', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'criterion_scores',
                'unique_together': {('session', 'criterion')},
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['student', 'assessment_date'], name='assessment__student_518a41_idx'),
        ),
    ]
