# Generated by Django 4.2.30 on 2026-07-11 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('sessions_completed', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_entries', to='students.student')),
            ],
            options={
                'db_table': 'coach_entries',
                'ordering': ['-assessment_date'],
                'unique_together': {('student', 'coach', 'assessment_date')},
            },
        ),
        migrations.CreateModel(
            name='CoachCriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.criterion')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.coachentry')),
            ],
            options={
                'db_table': 'coach_criterion_scores',
                'unique_together': {('entry', 'criterion')},
            },
        ),
    ]
